apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ssg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sgnatjuk/agrocd.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
