apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_MASTER_SERVICE
              value: redis-master
            - name: REDIS_REPLICA_SERVICE
              value: redis-replica
          volumeMounts:
            - name: frontend-overrides
              mountPath: /var/www/html/controllers.js
              subPath: controllers.js
            - name: frontend-overrides
              mountPath: /var/www/html/guestbook.php
              subPath: guestbook.php
      volumes:
        - name: frontend-overrides
          configMap:
            name: guestbook-ui-overrides
