apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
labels:
  app: guestbook
  tier: frontend
spec:
  type: NodePort
  selector:
    app: guestbook
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000
