apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: default
labels:
  app: redis
  role: master
spec:
  selector:
    app: redis
    role: master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
