apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  namespace: default
labels:
  app: redis
  role: replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: slave
          image: redis:7-alpine
          # сразу запускаем как реплику мастера
          args: ["redis-server", "--replicaof", "redis-master", "6379"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 10
            periodSeconds: 10
