apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: default
  labels:
    app: redis
    role: replica
spec:
  selector:
    app: redis
    role: replica
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
# Алиас под старое имя, которое запрашивает php/guestbook
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: default
  labels:
    app: redis
    role: replica
spec:
  selector:
    app: redis
    role: replica
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
